# =============================================================================
# AKS Application Landing Zone - Configuration
# =============================================================================
# Generated by Deploy-AKSLandingZone interactive mode.
# Scenario: single_region_baseline
# Review and customize these values before running the bootstrap.
# =============================================================================

# -----------------------------------------------------------------------------
# Scenario
# -----------------------------------------------------------------------------
scenario = "single_region_baseline"

# Secondary region (multi-region scenarios only)
secondary_location = ""

# Landing zone type (corp = hub peering, online = standalone)
landing_zone_type = "online"

# -----------------------------------------------------------------------------
# Core Settings
# -----------------------------------------------------------------------------
subscription_id              = "f96403ae-7ef3-4e36-81a7-cb74a12ce667"
connectivity_subscription_id = "1722f280-2f89-42c1-a80f-9a4773491727"
tenant_id                    = "79ee578e-cb66-4cc6-b879-3ff4f6e34a55"
location                     = "swedencentral"
workload_name                = "akstest"
environment                  = "t01"

tags = {
  "costCenter"   = "IT"
  "owner"        = "platform-team"
  "application"  = "aks-landing-zone"
}

# -----------------------------------------------------------------------------
# Networking - Spoke VNet
# System and user node pools use separate subnets (AKS baseline best practice)
# -----------------------------------------------------------------------------
vnet_address_space = "10.10.0.0/16"

subnet_address_prefixes = {
  aks_system_nodes  = "10.10.0.0/24"
  aks_user_nodes    = "10.10.1.0/22"
  aks_api_server    = "10.10.5.0/28"
  app_gateway       = "10.10.6.0/24"
  private_endpoints = "10.10.7.0/24"
  ingress           = "10.10.8.0/24"
}

# Hub VNet peering (from your ALZ deployment)
hub_vnet_resource_id         = ""
hub_vnet_name                = ""
hub_vnet_resource_group_name = ""
hub_firewall_private_ip      = ""
use_remote_gateways          = false

# -----------------------------------------------------------------------------
# AKS Configuration
# -----------------------------------------------------------------------------
kubernetes_version = "1.31"
aks_sku_tier       = "Standard"
availability_zones = ["1", "2", "3"]

# Network plugin
network_plugin      = "azure"
network_plugin_mode = "overlay"
network_policy      = "calico"

# IP ranges
service_cidr   = "172.16.0.0/16"
dns_service_ip = "172.16.0.10"
pod_cidr       = "192.168.0.0/16"

# Private cluster
private_cluster_enabled             = false
private_cluster_public_fqdn_enabled = false
private_dns_zone_id                 = "system"

# API server VNet integration
enable_api_server_vnet_integration = true
api_server_authorized_ip_ranges    = []

# Entra ID admin groups
aks_admin_group_object_ids = ["2a151a66-e0ce-455a-bae5-8a21513e3004"]

# Auto-upgrade
automatic_upgrade_channel = "patch"
node_os_upgrade_channel   = "NodeImage"

# Maintenance window
maintenance_window = {
  frequency   = "Weekly"
  interval    = 1
  duration    = 4
  day_of_week = "Sunday"
  start_time  = "02:00"
  utc_offset  = "+01:00"
}

# -----------------------------------------------------------------------------
# System Node Pool (dedicated subnet: snet-aks-system-*)
# Regulated scenarios: min_count=3 for higher HA
# -----------------------------------------------------------------------------
system_node_pool = {
  vm_size         = "Standard_D4ds_v5"
  os_disk_size_gb = 128
  os_disk_type    = "Ephemeral"
  max_pods        = 110
  min_count       = 2
  max_count       = 5
  node_count      = 2
  max_surge       = "33%"
}

# -----------------------------------------------------------------------------
# User Node Pool (dedicated subnet: snet-aks-user-*)
# Regulated scenarios: min_count=3 for higher HA + compliance label
# -----------------------------------------------------------------------------
user_node_pool = {
  vm_size         = "Standard_D4ds_v5"
  os_disk_size_gb = 128
  os_disk_type    = "Ephemeral"
  max_pods        = 110
  min_count       = 2
  max_count       = 20
  node_count      = 2
  max_surge       = "33%"
  node_labels = {
    "workload" = "user"
  }
}

# -----------------------------------------------------------------------------
# Identity & Security
# -----------------------------------------------------------------------------
enable_workload_identity = true
enable_azure_rbac        = true
disable_local_accounts   = true
enable_image_cleaner     = true
enable_azure_policy      = true
enable_defender          = true

# -----------------------------------------------------------------------------
# Monitoring
# -----------------------------------------------------------------------------
enable_managed_prometheus  = true
enable_managed_grafana     = true
enable_diagnostic_settings = true

# -----------------------------------------------------------------------------
# Scaling
# -----------------------------------------------------------------------------
enable_keda                   = true
enable_vpa                    = false
enable_node_auto_provisioning = false

# -----------------------------------------------------------------------------
# Networking Features
# -----------------------------------------------------------------------------
enable_app_gateway                        = true
enable_istio_service_mesh                 = false
istio_internal_ingress_gateway            = false
istio_external_ingress_gateway            = false
enable_application_gateway_for_containers = false
enable_nginx_ingress                      = false

# -----------------------------------------------------------------------------
# Storage
# -----------------------------------------------------------------------------
enable_blob_csi_driver    = true
enable_disk_csi_driver    = true
enable_file_csi_driver    = true
enable_snapshot_controller = true

# -----------------------------------------------------------------------------
# GitOps & Extensions
# -----------------------------------------------------------------------------
enable_flux = false
enable_dapr = false

# -----------------------------------------------------------------------------
# Compliance
# -----------------------------------------------------------------------------
enable_fips          = false
enable_backup        = false
enable_cost_analysis = false

# -----------------------------------------------------------------------------
# Application Gateway with WAF v2
# -----------------------------------------------------------------------------
waf_mode                 = "Prevention"
app_gateway_min_capacity = 1
app_gateway_max_capacity = 10

# -----------------------------------------------------------------------------
# Azure Container Registry
# -----------------------------------------------------------------------------
acr_zone_redundancy_enabled    = true
acr_retention_days             = 30
enable_acr_geo_replication      = false
acr_private_dns_zone_ids       = []
keyvault_private_dns_zone_ids  = []

# -----------------------------------------------------------------------------
# Monitoring Configuration
# -----------------------------------------------------------------------------
log_retention_days    = 90
grafana_sku           = "Standard"
grafana_zone_redundancy = true
grafana_public_access   = true
grafana_admin_group_object_id = "2a151a66-e0ce-455a-bae5-8a21513e3004"
